import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/app/globals.css'
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import theme from "@/utils/theme";
import {ThemeProvider} from "@mui/system";
import {Header} from "@/components/_layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        <ThemeProvider theme={theme}>
            <Header/>
          {children}
        </ThemeProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
